name: pygbag_build
on:
  workflow_dispatch:

jobs:
  build-pygbag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pygbag
        run: pip install pygbag

      - name: Clean old build
        run: rm -rf build

      - name: Build for web
        run: python -m pygbag --build main.py --target web

      - name: Verify build output
        run: ls -R build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/web
